### PR TITLE
Fix the library for the more recent realm versions

### PR DESCRIPTION
**Pull request by vork**

### CODE REVIEW

**Comment by McPo** [comment]
You need to remove the ColumnType import from RealmClusterManager.java

**Comment by vork** [comment]
@McPo thanks forgot to remove the import. Fixed.

**Comment by McPo** [comment]
On another note, I don't believe this is related directly to the changes you made as its breaks on the old HEAD as well. However it may another issue caused with a recent realm update.

When launching the application it crashes with the following stacktrace

>  Rejecting re-init on previously-failed class java.lang.Class<io.realm.RealmClusterManager>
         AndroidRuntime  D  Shutting down VM
                         E  FATAL EXCEPTION: main
                         E  Process: uk.ac.qub.quibe, PID: 23035
                         E  java.lang.NoClassDefFoundError: io.realm.RealmClusterManager
                         E      at co.moonmonkeylabs.realmmapview.RealmClusterMapFragment.setUpMapIfNeeded(RealmClusterMapFragment.java:167)
                         E      at co.moonmonkeylabs.realmmapview.RealmClusterMapFragment.onViewCreated(RealmClusterMapFragment.java:68)
                         E      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1046)
                         E      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
                         E      at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1332)
                         E      at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2288)
                         E      at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
                         E      at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:357)
                         E      at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:31)
                         E      at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:80)
                         E      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
                         E      at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                         E      at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                         E      at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                         E      at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                         E      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
                         E      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                         E      at uk.ac.qub.quibe.ui.activities.MainActivity.onCreate(MainActivity.java:18)
                         E      at android.app.Activity.performCreate(Activity.java:5990)
                         E      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                         E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                         E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                         E      at android.app.ActivityThread.access$800(ActivityThread.java:151)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                         E      at android.os.Handler.dispatchMessage(Handler.java:102)
                         E      at android.os.Looper.loop(Looper.java:135)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5254)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at java.lang.reflect.Method.invoke(Method.java:372)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

Just posting for visibility.
Did you test the changes yourself? I assume they were sucessfull.

Cheers,
Emmet

**Comment by thorbenprimke** [comment]
Thanks for the PR @vork. I have updated the library to Realm 1.0 now. I apologize I didn't merge this in a long time ago.

**Pull request closed without merging**
